In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [2]:
import numpy as np
arr1 = np.array([[2,3], [4,5]])
print("arr1=", arr1)
arr2 = np.array([[5,6], [7,8]])
print("arr2=",arr2)
print("after coccatenation = ")
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

arr1= [[2 3]
 [4 5]]
arr2= [[5 6]
 [7 8]]
after coccatenation = 
[[2 3 5 6]
 [4 5 7 8]]


In [3]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
print("arr1=", arr1)
arr2 = np.array([[5,6],[6,4]])
print("arr2=", arr2)
print("after concatenation = ")
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

arr1= [[1 2]
 [3 4]]
arr2= [[5 6]
 [6 4]]
after concatenation = 
[[1 2]
 [3 4]
 [5 6]
 [6 4]]


In [4]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [5]:
a = np.array([1,2,3])
b = np.array([4,6,5])
print("hstack =", np.hstack((a,b)))
print("vstack =", np.vstack((a,b)))
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print("hstack =",np.hstack((a,b)))
print("vstack =",np.vstack((a,b)))

hstack = [1 2 3 4 6 5]
vstack = [[1 2 3]
 [4 6 5]]
hstack = [[1 4]
 [2 5]
 [3 6]]
vstack = [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
