In [1]:
import numpy as np
arr = np.array([1,2,3,4])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [2]:
import numpy as np
arr = np.array([1,5,3,5])
newarr = np.array_split(arr , 4)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1]
[5]
[3]


In [3]:
import numpy as np
arr = np.array([[1,4],[4,6],[4,6],[5,6]])
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[1]


[5]


[3]


In [4]:
import numpy as np
arr = np.array([[1,4,5],[4,6,6],[4,6,7],[5,6,6]])
newarr = np.array_split(arr,4)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 4 5]]


[[4 6 6]]


[[4 6 7]]


In [5]:
import numpy as np
arr = np.array([[1,4,5],[4,6,6],[4,6,7],[5,6,6]])
newarr = np.array_split(arr,4, axis=1)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1]
 [4]
 [4]
 [5]]


[[4]
 [6]
 [6]
 [6]]


[[5]
 [6]
 [7]
 [6]]


In [6]:
import numpy as np
arr = np.array([[1,4,5],[4,6,6],[4,6,7],[5,6,6]])
newarr = np.vsplit(arr,4)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 4 5]]


[[4 6 6]]


[[4 6 7]]
