In [1]:
import numpy as np
arr = np.array([1,2,34,5])
print(arr[2:4])

[34  5]


In [2]:
import numpy as np
arr = np.array([1,2,34,5])
print(arr[1:4])

[ 2 34  5]


In [4]:
import numpy as np
arr = np.array([1,2,34,5])
print(arr[-4:-1])

[ 1  2 34]


In [5]:
import numpy as np
arr = np.array([1,2,3])
print(arr[1:3:2])

[2]


In [6]:
import numpy as np
arr = np.array([1,2,34,5])
print(arr[::2])

[ 1 34]


In [8]:
import numpy as np
arr = np.array([[1,2,34,5],[6,7,8,6]])
print(arr[1, 1:4])

[7 8 6]


In [11]:
import numpy as np
arr = np.array([[1,2,3,5],[7,8,9,4],[2,4,6,7]])
print(arr[2,0:2])

[2 4]


In [12]:
import numpy as np
arr = np.array([[1,2,3,5],[6,7,8,8]])
print(arr[0:2,1:4])

[[2 3 5]
 [7 8 8]]
